`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
 /////////////////////////////////////////////////////////////////////////////////////
 //
 // Module DESCRAMBLER_64B66B
 // Generated by Xilinx Aurora 64B66B
 // RR January 9, 2023.  Copied this from the Xilinx-generated source, but 
 //  changed the bit ordering (line 57) because the 
 
 `timescale 1ns / 1ps
 //***********************************Entity Declaration*******************************
 
 module descrambler_tpx4
 (
     // User Interface
     SCRAMBLED_DATA_IN,
     UNSCRAMBLED_DATA_OUT,
     DATA_VALID_IN,
 
     // System Interface
     USER_CLK,
     
     SYSTEM_RESET
 );
 
 //***********************************Port Declarations*******************************
 parameter RX_DATA_WIDTH = 64;
    // User Interface
     input   [0:(RX_DATA_WIDTH-1)] SCRAMBLED_DATA_IN;
     
     input                         DATA_VALID_IN;
     output  [(RX_DATA_WIDTH-1):0] UNSCRAMBLED_DATA_OUT;
 
       // System Interface
       input              USER_CLK; 
       input              SYSTEM_RESET; 

     
 
 //***************************Internal Register Declarations********************
 
     reg     [57:0]                 descrambler;
     integer                        i;
     reg     [57:0]                 poly;
     reg     [0:(RX_DATA_WIDTH-1)]  tempData;
     reg     [(RX_DATA_WIDTH-1):0]  unscrambled_data_i;
     reg                            xorBit;
 
 //*********************************Main Body of Code***************************
 
     always @(descrambler,SCRAMBLED_DATA_IN)
     begin
             poly = descrambler;
             //This was reversed for the bit ordering of TPX4
             //for (i=0;i<=(RX_DATA_WIDTH-1);i=i+1)
             for (i=(RX_DATA_WIDTH-1);i >=0; i=i-1)
             begin
                 xorBit = SCRAMBLED_DATA_IN[i] ^ poly[38] ^ poly[57];
                 poly = {poly[56:0],SCRAMBLED_DATA_IN[i]};
                 tempData[i] = xorBit;
             end
     end
 
     always @(posedge USER_CLK)
     begin
         if (SYSTEM_RESET)
         begin
             unscrambled_data_i <= 'h0;
             descrambler        <= 58'h155_5555_5555_5555;
         end
         else if (DATA_VALID_IN)
         begin
             unscrambled_data_i <= tempData;
             descrambler        <= poly;
         end
     end
 
     //________________ Scrambled Data assignment to output port _______________   
     assign UNSCRAMBLED_DATA_OUT = unscrambled_data_i;
 
 endmodule
 

